namespace RoofEstimation.Entities.Enums;

public enum MaterialsType
{
    BundlesOfMaterials,
    TrebuildStarter,
    DecoRidge,
    Nosing2x2,
    Nosing3x2,
    SafeGuard,
    Felt30lb,
    Valley,
    RidgeVentRoll,
    OCLowProfile,
    ShakeBaseAndCollars1point5,
    ShakeBaseAndCollars2,
    ShakeBaseAndCollars3,
    TTop4,
    HoodVent2Ppc4,
    HoodVent2Ppc6,
    TTop6,
    TTop7,
    HoodVent2Ppc8,
    OvalVertical,
    OvalHorizontal,
    PipesOther,
    StepFlashing,
    RoofToWalls,
    PeelAndStickBase,
    PeelAndStickCap,
    Nails3by4,
    Nails1by4,
    SiliconFlexiseal,
    TackerStaples,
    Paint,
    PlyWood7by16OSB,
    StaplesN1911by2,
}